### ISSUE TITLE
"Observe one of the test is failing: `message: 'with operators with different precedences'`"  in the simple.test.js

### ISSUE THREAD

**Issue by Oluwasetemi** [chidiwilliams/expression-evaluator#1]
Just try to understand the codebase and how everything works then I ran into one of the test that was failing. 

![image](https://user-images.githubusercontent.com/10030028/111207397-dd245a80-85c9-11eb-9f7b-b5b8768cd9c3.png)

```
{
    input: '24 + 5 * (6 - 3 ^ 2 ^ 2)',
    tokens: [24, '+', 5, '*', '(', 6, '-', 3, '^', 2, '^', 2, ')'],
    rpn: [24, 5, 6, 3, 2, 2, '^', '^', '-', '*', '+'],
    output: -351,
    message: 'with operators with different precedences',
  }
```

rpn function return [24, 5, 6, 3, 2, ^, '2', '^', '-', '*', '+'],
![image](https://user-images.githubusercontent.com/10030028/111207632-296f9a80-85ca-11eb-8fc9-c7371dbf0fc4.png)

**Comment by chidiwilliams** [comment]
Thanks for this. Looks like I changed something in the implementation and forgot to update the test. Should be fixed now.
