### ISSUE TITLE
Parenthesis precedence

### ISSUE THREAD

**Issue by ubitux** [chidiwilliams/expression-evaluator#2]
Hi,

I don't know if that's on purpose, but `shouldUnwindOperatorStack()` may end up doing `precedence['(']` (with a simple valid expression such as `(3+1)` it will happen when reaching the `+`), but no such character exists in the `precedence` dictionary. Fortunately, the comparison will evaluate as `false` all the time because of some weird behavior in js:

```
js> const foo = {'x': 3}
js> foo['x'] >= foo['y']
false
js> foo['x'] <= foo['y']
false
js>
```

I'm not sure if that was written on purpose, but that's pretty confusing for someone not coming from the Javascript world.

I spotted that because traditionally the Shunting-yard algorithm seems to explicit this case (https://en.wikipedia.org/wiki/Shunting-yard_algorithm#The_algorithm_in_detail, "there is an operator o2 other than the left parenthesis at the top") and was pretty confused not to find any mention here.

I see 2 solutions here, either add the parenthesis (or only the opening one?) in the `precedence` dict, or add special case for it like the reference algorithm on Wikipedia.

Or maybe that's perfectly valid javascript and this issue can be closed.

**Comment by chidiwilliams** [comment]
Thanks for pointing this out. I'm aware of that behaviour in JS, but it wasn't intentional to use it that way. Added an extra check here: https://github.com/chidiwilliams/expression-evaluator/commit/091ad9e1cbc266da684e2c4aacbf276062d8eea6.
